server:
    port: 7777
spring:
    application:
      name: config-dev
eureka:
    client:
      service-url:
        defaultZone: http://eureka7001:7001/eureka
config:
    info: "男儿当自强,山有木兮木有枝,心悦君兮君不知"
